/*
 * This file is part of Just Enough BrewCraft.
 *
 * Just Enough BrewCraft is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Just Enough BrewCraft is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Just Enough BrewCraft.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.pearx.jebc;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import org.apache.logging.log4j.Logger;

import java.util.Collections;

@Mod(name = Jebc.NAME, modid = Jebc.MODID, version = Jebc.VERSION, acceptedMinecraftVersions = Jebc.ACCEPTED_MINECRAFT_VERSIONS, dependencies = Jebc.DEPENDENCIES)
public class Jebc {
    @Mod.Instance
    public static Jebc INSTANCE;

    public static final String NAME = "Just Enough BrewCraft";
    public static final String MODID = "jebc";
    public static final String VERSION = "";
    public static final String DESCRIPTION = "";
    public static final String ACCEPTED_MINECRAFT_VERSIONS = "";
    public static final String DEPENDENCIES = "";

    private Logger log;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e) {
        log = e.getModLog();
        setupMetadata(e.getModMetadata());
    }

    private void setupMetadata(ModMetadata d) {
        d.autogenerated = false;
        d.authorList = Collections.singletonList("mrapplexz");
        d.description = DESCRIPTION;
        d.version = VERSION;
        d.modId = MODID;
        d.name = NAME;
        d.logoFile = "assets/jebc/logo.png";
        d.url = "https://www.curseforge.com/minecraft/mc-mods/just-enough-brewcraft";
    }

    public Logger getLog() {
        return log;
    }
}
